language: python
python:
- '3.6'
install: pip install -e .
script:
- pip install -r requirements.txt
deploy:
  provider: pypi
  user: creditas
  password:
    secure: GxIuDzVVtZp6yZph1+WCIqW7nXtHcmGTV7mKcOYwfuk2Hg7A/6TAdwcfhex2ZsNpkrSqXAg7niztV0D+gfE8OwwlRnlGEDMnqckFr1oWbNreCRqV2pZpuowQsIcxVTk4fWYhswh5zsnSYuAlytocCWsFNNf8odOCGORpVU71FZITCM/nYfTzVzokrB6oyIwjkjDfzX0AuzEe+BUqS42CHC+nYCHRjI8YvWMlwMt6n6LPJVNxydECrhDYowT2ERHGJRc75oolX/q/LwnJPu8pNWjbFjCdmfBGvnprnUxfkxP+C10H/0SfSij7U+1NP9MJz9zLUaPekRtWVAiW8nMr7WF/oUmfKvbWj+uLcyVGuYabrwktaA22GFqIJiurGYLYZjF/9XC4VWqwHULghHbvV25Rnm8esys8N37QWrT9vQt1ZARk6OhpQcpmKs8eR5fCmdQnkW1xXN5Gl7mZJikvPv28VE3R7RB3swdOfhb8Bs9e1fSI45IVmrlCrtlDu9s8O9tC84FV3xUOtozLxU8Fsc9bv3J0lvXjhEQ9WQTCWbZKIf695sR+Qr7GZTMiS4yy9swagharYWcM9VSrXcmqStAkOStmzRawFrtZc57LlRMqd8wYGlI+XWkFM6kFRgqto6HRuZDQdlPx8r6FdiUiqF2ionwSgEN1uIvw5WgMKlY=
  true:
    branch: master
